# Generated by Django 5.1.4 on 2024-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_coment', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
