# Generated by Django 5.1.4 on 2024-12-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_coment',
            new_name='contact_comment',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_mail',
            new_name='contact_email',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
